# Generated by Django 2.2.7 on 2019-12-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField(max_length=300)),
                ('shortened_url', models.TextField(max_length=300)),
            ],
        ),
    ]
