# Generated by Django 2.2.7 on 2019-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_url',
            field=models.TextField(db_index=True, max_length=300, unique=True),
        ),
    ]
