# Generated by Django 2.2.7 on 2019-12-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20191209_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
